default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0

joint_limits:
  leftarm_shoulder_pan_joint:
    has_position_limits: true
    min_position: -3.14
    max_position: 0.0
    has_velocity_limits: true
    max_velocity: 2.792527
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_deceleration_limits: true
    max_deceleration: -5.0
    has_jerk_limits: false
    max_jerk: 6.0
    has_effort_limits: true
    max_effort: 56.0
  leftarm_shoulder_lift_joint:
    has_position_limits: true
    min_position: -1.78
    max_position: 1.78
    has_velocity_limits: true
    max_velocity: 2.792527
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_deceleration_limits: true
    max_deceleration: -5.0
    has_jerk_limits: false
    max_jerk: 6.0
    has_effort_limits: true
    max_effort: 56.0
  leftarm_elbow_joint:
    has_position_limits: true
    min_position: -1.53
    max_position: 2.28
    has_velocity_limits: true
    max_velocity: 2.792527
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_deceleration_limits: true
    max_deceleration: -5.0
    has_jerk_limits: false
    max_jerk: 6.0
    has_effort_limits: true
    max_effort: 56.0
  leftarm_wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 2.792527
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_deceleration_limits: true
    max_deceleration: -5.0
    has_jerk_limits: false
    max_jerk: 6.0
    has_effort_limits: true
    max_effort: 56.0
  leftarm_wrist_2_joint:
    has_position_limits: true
    min_position: -1.57
    max_position: 1.57
    has_velocity_limits: true
    max_velocity: 2.792527
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_deceleration_limits: true
    max_deceleration: -5.0
    has_jerk_limits: false
    max_jerk: 6.0
    has_effort_limits: true
    max_effort: 56.0
  leftarm_wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 2.792527
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_deceleration_limits: true
    max_deceleration: -5.0
    has_jerk_limits: false
    max_jerk: 6.0
    has_effort_limits: true
    max_effort: 56.0

  rightarm_shoulder_pan_joint:
    has_position_limits: true
    min_position: 0.0
    max_position: 3.14
    has_velocity_limits: true
    max_velocity: 2.792527
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_deceleration_limits: true
    max_deceleration: -5.0
    has_jerk_limits: false
    max_jerk: 6.0
    has_effort_limits: true
    max_effort: 56.0
  rightarm_shoulder_lift_joint:
    has_position_limits: true
    min_position: -1.78
    max_position: 1.78
    has_velocity_limits: true
    max_velocity: 2.792527
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_deceleration_limits: true
    max_deceleration: -5.0
    has_jerk_limits: false
    max_jerk: 6.0
    has_effort_limits: true
    max_effort: 56.0
  rightarm_elbow_joint:
    has_position_limits: true
    min_position: -1.53
    max_position: 2.28
    has_velocity_limits: true
    max_velocity: 2.792527
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_deceleration_limits: true
    max_deceleration: -5.0
    has_jerk_limits: false
    max_jerk: 6.0
    has_effort_limits: true
    max_effort: 56.0
  rightarm_wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 2.792527
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_deceleration_limits: true
    max_deceleration: -5.0
    has_jerk_limits: false
    max_jerk: 6.0
    has_effort_limits: true
    max_effort: 56.0
  rightarm_wrist_2_joint:
    has_position_limits: true
    min_position: -1.57
    max_position: 1.57
    has_velocity_limits: true
    max_velocity: 2.792527
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_deceleration_limits: true
    max_deceleration: -5.0
    has_jerk_limits: false
    max_jerk: 6.0
    has_effort_limits: true
    max_effort: 56.0
  rightarm_wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 2.792527
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_deceleration_limits: true
    max_deceleration: -5.0
    has_jerk_limits: false
    max_jerk: 6.0
    has_effort_limits: true
    max_effort: 56.0
