controller_manager:
  ros__parameters:
    update_rate: 40
    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    joint_group_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
    gripper_action_controller:
      type: position_controllers/GripperActionController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    right_arm_pid_controller:
      type: pid_controller/PidController

left_arm_controller:
  ros__parameters:
    joints:
      - leftarm_shoulder_pan_joint
      - leftarm_shoulder_lift_joint
      - leftarm_elbow_joint
      - leftarm_wrist_1_joint
      - leftarm_wrist_2_joint
      - leftarm_wrist_3_joint
    command_interfaces: [position]
    state_interfaces: [position, velocity]
    allow_partial_joints_goal: true
    
    constraints:
      goal_time: 2.0
      stopped_velocity_tolerance: 0.01
      leftarm_shoulder_pan_joint:
        goal: 0.01
    pid_gains:
      leftarm_shoulder_pan_joint:
        p: 100.0
        i: 0.0
        d: 10.0
      leftarm_shoulder_lift_joint:
        p: 100.0
        i: 0.0
        d: 10.0
    open_loop_control: false
    allow_integration_in_goal_trajectories: true
    allow_nonzero_velocity_at_trajectory_end: true

right_arm_controller:
  ros__parameters:
    joints:
      - rightarm_shoulder_pan_joint
      - rightarm_shoulder_lift_joint
      - rightarm_elbow_joint
      - rightarm_wrist_1_joint
      - rightarm_wrist_2_joint
      - rightarm_wrist_3_joint
    command_interfaces: [position]
    state_interfaces: [position, velocity]
    allow_partial_joints_goal: true
    constraints:
      goal_time: 2.0
      stopped_velocity_tolerance: 0.01
      rightarm_shoulder_pan_joint:
        goal: 0.01
    gains:
      rightarm_shoulder_pan_joint:
        p: 2000.0
        i: 0.0
        d: 1000.0
      rightarm_shoulder_lift_joint:
        p: 2000.0
        i: 0.0
        d: 1000.0
      rightarm_elbow_joint:
        p: 2000.0
        i: 0.0
        d: 1000.0
    open_loop_control: false
    allow_integration_in_goal_trajectories: true
    allow_nonzero_velocity_at_trajectory_end: true

joint_group_velocity_controller:
  ros__parameters:
    joints:
      - leftarm_shoulder_pan_joint
      - leftarm_shoulder_lift_joint
      - leftarm_elbow_joint
      - leftarm_wrist_1_joint
      - leftarm_wrist_2_joint
      - leftarm_wrist_3_joint
    command_interfaces: [velocity]
    state_interfaces: [position, velocity]
    constraints:
      stopped_velocity_tolerance: 0.01

gripper_action_controller:
  ros__parameters:
    joint: gripper_controller
    action_monitor_rate: 20.0
    goal_tolerance: 0.01
    max_effort: 100.0
    allow_stalling: false
    stall_velocity_threshold: 0.001
    stall_timeout: 1.0


right_arm_pid_controller:
  ros__parameters:
    dof_names:
      - rightarm_shoulder_pan_joint
      - rightarm_shoulder_lift_joint
      - rightarm_elbow_joint
      - rightarm_wrist_1_joint
      - rightarm_wrist_2_joint
      - rightarm_wrist_3_joint

    command_interface: position

    reference_and_state_interfaces: position

    gains:
      rightarm_shoulder_pan_joint:
        p: 10.0
        i: 0.0
        d: 5.0
      rightarm_shoulder_lift_joint:
        p: 10.0
        i: 0.0
        d: 5.0
      rightarm_elbow_joint:
        p: 10.0
        i: 0.0
        d: 5.0
      rightarm_wrist_1_joint:
        p: 10.0
        i: 0.0
        d: 5.0
      rightarm_wrist_2_joint:
        p: 10.0
        i: 0.0
        d: 5.0
      rightarm_wrist_3_joint:
        p: 10.0
        i: 0.0
        d: 5.0