moveit_servo:
  move_group_name: leftarm
  active_subgroup: left_arm_w1
  planning_frame: base_link
  ee_frame_name: leftarm_wrist_1_link
  robot_link_command_frame: base_link
  command_in_type: speed_units
  cartesian_command_in_topic: /delta_twist_cmds
  command_out_type: trajectory_msgs/JointTrajectory
  command_out_topic: /left_arm_controller/joint_trajectory
  publish_period: 0.01
  low_latency_mode: true
  check_collisions: true
  joint_limit_margin: 0.05
  linear_scale: 0.75
  rotational_scale: 0.75
  joint_topic: /joint_states
  status_topic: ~/status
  num_outgoing_halt_msgs_to_publish: 1
  publish_joint_positions: true
  publish_joint_velocities: false
  publish_joint_accelerations: false
