planning_plugins:
  - ompl_interface/OMPLPlanner

# To optionally use Ruckig for jerk-limited smoothing, add this line to the request adapters below
# default_planner_request_adapters/AddRuckigTrajectorySmoothing
request_adapters:
  - default_planning_request_adapters/ResolveConstraintFrames
  - default_planning_request_adapters/ValidateWorkspaceBounds
  - default_planning_request_adapters/CheckStartStateBounds
  - default_planning_request_adapters/CheckStartStateCollision
response_adapters:
  - default_planning_response_adapters/AddTimeOptimalParameterization
  - default_planning_response_adapters/ValidateSolution
  - default_planning_response_adapters/DisplayMotionPath

planner_configs:
  APSConfigDefault:
    type: geometric::AnytimePathShortening
    shortcut: 1
    hybridize: 1
    max_hybrid_paths: 36
    num_planners: 8
    planners: "RRTConnect,RRTConnect,RRTConnect,RRTConnect,RRTConnect,RRTConnect,RRTConnect,RRTConnect"

  SBLkConfigDefault:
    type: geometric::SBL
    range: 0.0

  ESTkConfigDefault:
    type: geometric::EST
    range: 0.0
    goal_bias: 0.05

  LBKPIECEkConfigDefault:
    type: geometric::LBKPIECE
    range: 0.0
    border_fraction: 0.9
    min_valid_path_fraction: 0.5

  BKPIECEkConfigDefault:
    type: geometric::BKPIECE
    range: 0.0
    border_fraction: 0.9
    failed_expansion_score_factor: 0.5
    min_valid_path_fraction: 0.5

  KPIECEkConfigDefault:
    type: geometric::KPIECE
    range: 0.0
    goal_bias: 0.05
    border_fraction: 0.9
    failed_expansion_score_factor: 0.5
    min_valid_path_fraction: 0.5

  RRTkConfigDefault:
    type: geometric::RRT
    range: 0.0
    goal_bias: 0.05

  RRTConnectkConfigDefault:
    type: geometric::RRTConnect
    range: 0.0

  RRTstarkConfigDefault:
    type: geometric::RRTstar
    range: 0.0
    goal_bias: 0.05
    delay_collision_checking: 1

  TRRTkConfigDefault:
    type: geometric::TRRT
    range: 0.0
    goal_bias: 0.05
    max_states_failed: 10
    temp_change_factor: 2.0
    min_temperature: 1.0e-9
    init_temperature: 1.0e-5
    frountier_threshold: 0.0
    frountierNodeRatio: 0.1
    k_constant: 0.0

  PRMkConfigDefault:
    type: geometric::PRM
    max_nearest_neighbors: 10

  PRMstarkConfigDefault:
    type: geometric::PRMstar

  FMTkConfigDefault:
    type: geometric::FMT
    num_samples: 1000
    radius_multiplier: 1.1
    nearest_k: 1
    cache_cc: 1
    heuristics: 0
    extended_fmt: 1

  BFMTkConfigDefault:
    type: geometric::BFMT
    num_samples: 1000
    radius_multiplier: 1.0
    nearest_k: 1
    balanced: 0
    optimality: 1
    heuristics: 1
    cache_cc: 1
    extended_fmt: 1

  PDSTkConfigDefault:
    type: geometric::PDST

  STRIDEkConfigDefault:
    type: geometric::STRIDE
    range: 0.0
    goal_bias: 0.05
    use_projected_distance: 0
    degree: 16
    max_degree: 18
    min_degree: 12
    max_pts_per_leaf: 6
    estimated_dimension: 0.0
    min_valid_path_fraction: 0.2

  BiTRRTkConfigDefault:
    type: geometric::BiTRRT
    range: 0.0
    temp_change_factor: 0.1
    init_temperature: 100
    frountier_threshold: 0.0
    frountier_node_ratio: 0.1
    cost_threshold: 1e300

  LBTRRTkConfigDefault:
    type: geometric::LBTRRT
    range: 0.0
    goal_bias: 0.05
    epsilon: 0.4

  BiESTkConfigDefault:
    type: geometric::BiEST
    range: 0.0

  ProjESTkConfigDefault:
    type: geometric::ProjEST
    range: 0.0
    goal_bias: 0.05

  LazyPRMkConfigDefault:
    type: geometric::LazyPRM
    range: 0.0

  LazyPRMstarkConfigDefault:
    type: geometric::LazyPRMstar

  SPARSkConfigDefault:
    type: geometric::SPARS
    stretch_factor: 3.0
    sparse_delta_fraction: 0.25
    dense_delta_fraction: 0.001
    max_failures: 1000

  SPARStwokConfigDefault:
    type: geometric::SPARStwo
    stretch_factor: 3.0
    sparse_delta_fraction: 0.25
    dense_delta_fraction: 0.001
    max_failures: 5000

  TrajOptDefault:
    type: geometric::TrajOpt

# --- your old groups (kept) ---
arm:
  default_planner_config: RRTConnectkConfigDefault
  planner_configs:
    - APSConfigDefault
    - SBLkConfigDefault
    - ESTkConfigDefault
    - LBKPIECEkConfigDefault
    - BKPIECEkConfigDefault
    - KPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - RRTstarkConfigDefault
    - TRRTkConfigDefault
    - PRMkConfigDefault
    - PRMstarkConfigDefault
    - FMTkConfigDefault
    - BFMTkConfigDefault
    - PDSTkConfigDefault
    - STRIDEkConfigDefault
    - BiTRRTkConfigDefault
    - LBTRRTkConfigDefault
    - BiESTkConfigDefault
    - ProjESTkConfigDefault
    - LazyPRMkConfigDefault
    - LazyPRMstarkConfigDefault
    - SPARSkConfigDefault
    - SPARStwokConfigDefault
    - TrajOptDefault

gripper:
  default_planner_config: RRTConnectkConfigDefault
  planner_configs:
    - APSConfigDefault
    - SBLkConfigDefault
    - ESTkConfigDefault
    - LBKPIECEkConfigDefault
    - BKPIECEkConfigDefault
    - KPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - RRTstarkConfigDefault
    - TRRTkConfigDefault
    - PRMkConfigDefault
    - PRMstarkConfigDefault
    - FMTkConfigDefault
    - BFMTkConfigDefault
    - PDSTkConfigDefault
    - STRIDEkConfigDefault
    - BiTRRTkConfigDefault
    - LBTRRTkConfigDefault
    - BiESTkConfigDefault
    - ProjESTkConfigDefault
    - LazyPRMkConfigDefault
    - LazyPRMstarkConfigDefault
    - SPARSkConfigDefault
    - SPARStwokConfigDefault
    - TrajOptDefault

arm_with_gripper:
  default_planner_config: RRTConnectkConfigDefault
  planner_configs:
    - APSConfigDefault
    - SBLkConfigDefault
    - ESTkConfigDefault
    - LBKPIECEkConfigDefault
    - BKPIECEkConfigDefault
    - KPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - RRTstarkConfigDefault
    - TRRTkConfigDefault
    - PRMkConfigDefault
    - PRMstarkConfigDefault
    - FMTkConfigDefault
    - BFMTkConfigDefault
    - PDSTkConfigDefault
    - STRIDEkConfigDefault
    - BiTRRTkConfigDefault
    - LBTRRTkConfigDefault
    - BiESTkConfigDefault
    - ProjESTkConfigDefault
    - LazyPRMkConfigDefault
    - LazyPRMstarkConfigDefault
    - SPARSkConfigDefault
    - SPARStwokConfigDefault
    - TrajOptDefault

# --- NEW: add your wrist-1 subgroup here ---
left_arm_w1:
  default_planner_config: RRTConnectkConfigDefault
  planner_configs:
    - RRTConnectkConfigDefault
  longest_valid_segment_fraction: 0.005
  # Helps OMPL for low-DoF arms; use two real joint names from this group:
  projection_evaluator: joints(leftarm_shoulder_pan_joint,leftarm_shoulder_lift_joint)
